"use client";

import Link from "next/link";
import { usePavel } from "@/components/pavel-provider";
import { ProtocolShell } from "@/components/protocol-shell";
import { EmptyState, PageHeader, Section, StatusBadge, TrustBoundary } from "@/components/protocol-ui";

export default function EvidencePage() {
  const { snapshot, snapshotLoading, snapshotError, refreshSnapshot } = usePavel();
  const records = snapshot?.intents.map((intent) => ({ intent, evidence: snapshot.evidence[intent.intent_id] })).filter((item) => item.evidence) ?? [];
  return <ProtocolShell><PageHeader eyebrow="EVIDENCE / PROVENANCE" title="See what was captured, not just where it came from." body="Every evidence definition commits an authority, URL, digest, byte length, policy fingerprint, and append-only sequence. The URL is transport; the identity is the committed snapshot." /><Section eyebrow="CANONICAL SNAPSHOTS" title="Evidence registry">{snapshotLoading ? <div className="read-panel read-loading"><span className="skeleton skeleton-wide" /><span className="skeleton skeleton-medium" /></div> : snapshotError ? <div className="read-panel read-error"><strong>Evidence reads unavailable</strong><p>{snapshotError}</p><button className="button button-secondary" type="button" onClick={() => void refreshSnapshot()}>Retry read</button></div> : records.length ? <div className="surface table-wrap"><table className="data-table"><thead><tr><th>Intent</th><th>Kind</th><th>Capture source</th><th>Identity</th><th>Status</th></tr></thead><tbody>{records.map(({ intent, evidence }) => <tr key={`${intent.intent_id}-${evidence?.evidence_id}`}><td><Link className="text-link" href={`/app/intents/${intent.intent_id}`}>{intent.intent_id}</Link><div className="mono">{intent.mandate_id}</div></td><td className="mono">{evidence?.evidence_kind}</td><td><strong>{evidence?.expected_authority}</strong><div className="mono">{evidence?.origin_url}</div></td><td><code>{evidence?.committed_sha256 || "Digest pending"}</code><div className="mono">{evidence?.committed_byte_length || "0"} bytes</div></td><td><StatusBadge status={intent.status === "EVIDENCE_READY" || intent.status === "AUTHORIZED" || intent.status === "FULFILLED" ? "EVIDENCE_READY" : "EVIDENCE_PENDING"} /></td></tr>)}</tbody></table></div> : <EmptyState title="No evidence definitions found" body="Evidence is created from an Intent detail page after the proposal is submitted." action={<Link className="button button-primary" href="/app/intents">Open intents</Link>} />}</Section><Section eyebrow="THE EVIDENCE CONTRACT" title="Authenticated means more than reachable"><div className="grid grid-3"><div className="metric-card"><span className="label">Authority</span><strong className="data-value">Bound</strong><span className="mono">Must match the sealed policy and counterparty</span></div><div className="metric-card"><span className="label">Identity</span><strong className="data-value">Digest + length</strong><span className="mono">Committed before semantic review</span></div><div className="metric-card"><span className="label">Sequence</span><strong className="data-value">Append-only</strong><span className="mono">Authorization and fulfillment remain distinct</span></div></div></Section><TrustBoundary title="Raw provenance is expandable" body="Use Advanced details on an Intent to inspect the exact JSON. Normal application views prioritize state, next action, and user-readable meaning." /></ProtocolShell>;
}
