"use client";

import { ProtocolShell } from "@/components/protocol-shell";
import { WriteForm } from "@/components/action-form";
import { EmptyState, Field, PageHeader, Section, StatusBadge, TrustBoundary } from "@/components/protocol-ui";
import { usePavel } from "@/components/pavel-provider";
import { CORE_ADDRESS } from "@/lib/pavel/network";

export default function DisputesPage() {
  const { snapshot, refreshSnapshot } = usePavel();
  const challengeable = snapshot?.intents.filter((intent) => ["FULFILLED", "NOT_FULFILLED", "DISPUTED", "ADJUDICATED_RELEASE", "ADJUDICATED_REFUND"].includes(intent.status)) ?? [];
  return <ProtocolShell><PageHeader eyebrow="DISPUTES / CHALLENGES" title="Make adverse evidence explicit." body="Challenges are append-only records with their own evidence, deadlines, qualification, and adjudication. Submission alone never silently rewrites settlement." /><Section eyebrow="CANONICAL INTENTS" title="Challenge surface">{challengeable.length ? <div className="grid grid-3">{challengeable.map((intent) => <div className="surface" key={intent.intent_id}><div className="section-title-row"><h3>{intent.intent_id}</h3><StatusBadge status={intent.status === "FULFILLED" ? "FULFILLED" : "NOT_FULFILLED"} /></div><p>{intent.title || intent.deliverable}</p><WriteForm submitLabel="Open challenge" request={(values) => ({ actionKey: `core:open-dispute:${intent.intent_id}:${values.reason}`, contract: CORE_ADDRESS, method: "open_dispute", args: [intent.intent_id, values.reason], targetState: "Challenge submitted" })} onSubmitted={() => void refreshSnapshot()}><Field label="Reason"><textarea name="reason" placeholder="Explain the material challenge" required /></Field></WriteForm></div>)}</div> : <EmptyState title="No challengeable intents" body="Challenges become available only after a fulfillment result or a resolved challenge state." />}</Section><Section eyebrow="RECOVERY MODEL" title="Deadline-aware, not destructive"><div className="grid grid-3"><div className="metric-card"><span className="label">Submission</span><strong className="data-value">Append-only</strong><span className="mono">Original fulfillment remains visible</span></div><div className="metric-card"><span className="label">Qualification</span><strong className="data-value">Evidence-bound</strong><span className="mono">Snapshots must match policy and intent</span></div><div className="metric-card"><span className="label">Adjudication</span><strong className="data-value">Direction only</strong><span className="mono">Core determines release or refund</span></div></div></Section><TrustBoundary title="Deadlines are protocol facts" body="The application hides actions after the canonical deadline. It does not let a browser extend a challenge window or choose a settlement recipient." /></ProtocolShell>;
}
