"use client";

import { useEffect, useState } from "react";
import { ProtocolShell } from "@/components/protocol-shell";
import { AdvancedDetails, EmptyState, PageHeader, Section, StatusBadge, TrustBoundary } from "@/components/protocol-ui";
import { allTransactions, TRANSACTION_EVENT, type StoredTransaction } from "@/lib/genlayer/transaction-store";
import { explorerTransactionUrl } from "@/lib/pavel/network";

export default function ActivityPage() {
  const [items, setItems] = useState<StoredTransaction[]>([]);
  useEffect(() => { const load = () => setItems(allTransactions()); load(); window.addEventListener(TRANSACTION_EVENT, load); return () => window.removeEventListener(TRANSACTION_EVENT, load); }, []);
  return <ProtocolShell><PageHeader eyebrow="ACTIVITY / SAME-ID TRACKING" title="A transaction is a trace, not a spinner." body="Every write is persisted as soon as the wallet returns a transaction ID. This feed reconciles that same ID through protocol finality, execution, and canonical state readback." /><Section eyebrow="LOCAL TRANSACTION JOURNAL" title="Recent activity">{items.length ? <div className="surface table-wrap"><table className="data-table"><thead><tr><th>Action</th><th>Transaction ID</th><th>Contract</th><th>Stage</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.hash}><td><strong>{item.method.replaceAll("_", " ")}</strong><div className="mono">{new Date(item.submittedAt).toLocaleString()}</div></td><td><code>{item.hash}</code></td><td className="mono">{item.contract}</td><td><StatusBadge status={item.stage === "FINALIZED" ? "FINALIZED_SUCCESS" : item.stage === "EXECUTION_FAILED" ? "EXECUTION_FAILED" : item.stage === "AMBIGUOUS" ? "TRANSACTION_AMBIGUOUS" : "AUTHORIZATION_PENDING"} /></td><td><a className="text-link" href={explorerTransactionUrl(item.hash)} target="_blank" rel="noreferrer">Explorer ↗</a></td></tr>)}</tbody></table></div> : <EmptyState title="No local transactions yet" body="When you sign a PAVEL write, its returned ID will appear here immediately—even before finality." />}</Section><Section eyebrow="THE TRANSACTION EXPERIENCE" title="Review → wallet → readback"><div className="steps"><div className="step"><span className="step-number">01</span><h3>Review</h3><p>Contract, method, value, network, and target state are shown before signing.</p></div><div className="step"><span className="step-number">02</span><h3>Broadcast once</h3><p>A returned transaction ID is persisted before polling or refresh.</p></div><div className="step"><span className="step-number">03</span><h3>Reconcile</h3><p>Finalized is separated from execution success and canonical application state.</p></div></div></Section><AdvancedDetails><pre className="json-block">{JSON.stringify(items, null, 2)}</pre></AdvancedDetails><TrustBoundary title="No blind rebroadcast" body="An ambiguous poll is not permission to send a replacement. Resume reconciliation with the same transaction ID from this journal." /></ProtocolShell>;
}
