"use client";

import Link from "next/link";
import { ProtocolShell } from "@/components/protocol-shell";
import { WriteForm } from "@/components/action-form";
import { DataCard, EmptyState, Field, PageHeader, ReadState, Section, TrustBoundary } from "@/components/protocol-ui";
import { usePavel } from "@/components/pavel-provider";
import { VAULT_ADDRESS } from "@/lib/pavel/network";

export default function VaultPage() {
  const { snapshot, snapshotLoading, snapshotError, refreshSnapshot } = usePavel();
  const accounting = snapshot?.globalAccounting;
  return <ProtocolShell><PageHeader eyebrow="VAULT / ECONOMIC LEDGER" title="Custody with a visible accounting trail." body="Vault balances come from canonical latest-final reads. Core chooses the settlement direction; Vault executes only that direction." action={<a className="button button-primary" href="#deposit">Add funds</a>} /><ReadState loading={snapshotLoading} error={snapshotError} onRetry={() => void refreshSnapshot()}><div className="grid"><DataCard label="Total deposited" value={String(accounting?.deposited ?? "0")} note="Native GEN units" /><DataCard label="Available" value={String(accounting?.available ?? "0")} note="Ready to reserve" tone="accent" /><DataCard label="Reserved" value={String(accounting?.reserved ?? "0")} note="Locked to active intents" /><DataCard label="Release pending" value={String(accounting?.release_pending ?? "0")} note="External observation unconfirmed" tone="warning" /></div><Section eyebrow="BY MANDATE" title="Accounting domains">{snapshot?.mandates.length ? <div className="surface table-wrap"><table className="data-table"><thead><tr><th>Mandate</th><th>Deposited</th><th>Available</th><th>Reserved</th><th>Conservation</th></tr></thead><tbody>{snapshot.mandates.map((mandate) => { const item = snapshot.accounting[mandate.mandate_id]; return <tr key={mandate.mandate_id}><td><Link className="text-link" href={`/app/mandates/${mandate.mandate_id}`}>{mandate.mandate_id}</Link><div className="mono">{mandate.title || "Untitled mandate"}</div></td><td className="mono">{item?.deposited ?? "0"}</td><td className="mono">{item?.available ?? "0"}</td><td className="mono">{item?.reserved ?? "0"}</td><td className={item?.conserved ? "check-pass" : "status-danger"}>{item?.conserved ? "Conserved" : "Read unavailable"}</td></tr>; })}</tbody></table></div> : <EmptyState title="No accounting domains" body="A deposit is always bound to a canonical Mandate ID." />}</Section></ReadState><Section id="deposit" eyebrow="WRITE / PRINCIPAL" title="Deposit into a mandate"><WriteForm submitLabel="Review deposit" request={(values) => ({ actionKey: `vault:deposit:${values.mandate_id}:${values.amount}`, contract: VAULT_ADDRESS, method: "deposit", args: [values.mandate_id], value: BigInt(values.amount || "0"), targetState: "Vault available balance increased" })} onSubmitted={() => void refreshSnapshot()}><Field label="Mandate ID"><input name="mandate_id" placeholder="M-1" required /></Field><Field label="Deposit amount (native GEN units)" hint="The payable value is separate from the network fee shown by your wallet."><input name="amount" inputMode="numeric" placeholder="1" min="1" required /></Field></WriteForm><TrustBoundary title="Before signing" body="The deposit is sent to the deployed Vault address, never Core. The wallet controls the fee; the contract records the amount only after canonical execution." /></Section></ProtocolShell>;
}
